# Generated by Django 2.2.4 on 2019-08-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('mobile', models.CharField(max_length=12)),
                ('dob', models.DateField()),
                ('photo', models.ImageField(height_field=120, upload_to='image', width_field=100)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
