# Generated by Django 2.2.4 on 2019-09-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GetOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kotid', models.CharField(max_length=30)),
                ('item_name', models.CharField(max_length=30)),
                ('note', models.CharField(max_length=30)),
                ('qnty', models.CharField(max_length=3)),
                ('price', models.CharField(max_length=6)),
            ],
        ),
    ]
