# Generated by Django 2.2.4 on 2019-09-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_type',
        ),
    ]
